### PR TITLE
cudnn 8.1.0.77

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Should we grab the changes from PR ( https://github.com/conda-forge/cudnn-feedstock/pull/13 )?

**Comment by isuruf** [comment]
> Should we grab the changes from PR ( #13 )?

No, please wait until https://github.com/conda-forge/conda-smithy/pull/1453 is in

**Comment by jakirkham** [comment]
Those changes were just fixing the license message. Are we thinking of different changes?

**Comment by isuruf** [comment]
Oops. sorry, I meant adding `conda_build_config.yaml`.

**Comment by kkraus14** [comment]
> Oops. sorry, I meant adding `conda_build_config.yaml`.

Sorry, I'm not clear. Do you mean that I should remove the `conda_build_config.yaml` and wait until conda-forge/conda-smithy#1453 is in?

**Comment by jakirkham** [comment]
All good. Yeah that makes sense

Keith do you know how soon we need this?

**Comment by kkraus14** [comment]
> Keith do you know how soon we need this?

I'm trying to preemptively put out anticipated fires so I don't think it's critical 😆.

I saw this as a good opportunity for me to get some much needed experience in playing with using a `conda_build_config.yaml` file which is why I put in the PR, but happy to wait until other things land if that would be better.

**Comment by jakirkham** [comment]
Big fan of doing things preemptively. So thanks for getting this going 🙏

Yeah I think we are waiting on some upstream changes in conda-smithy that will make it easier to select OS. Though haven't caught up on that discussion personally. Hopefully Isuru can fill us in 🙂

**Comment by kkraus14** [comment]
Alright, will hold tight until I hear otherwise then. Anyone feel free to push to my branch as desired here 😄

**Comment by beckermr** [comment]
I just pushed the last bit to that smithy PR, so this should be on its way sometime tomorrow I think.

**Comment by jakirkham** [comment]
@beckermr, would you be able to advise on what we should do instead here? 🙂

Seems like conda-smithy got released. Though still a little unclear on how we should take that into account with our changes here. Do we change or remove `conda_build_config.yaml`? Is there anything else we need to add?

**Comment by beckermr** [comment]
@isuruf has a specific idea of what he wants to do here. I will defer to him.

**Review by kkraus14 — COMMENTED** [review]
Can't approve my own PR, but the changes from @isuruf look good. Thanks!

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by kkraus14** [comment]
@conda-forge/core Could someone review / merge this? It seems I'm the only maintainer on this now.

**Comment by jakirkham** [comment]
Thanks all! 😄

**Comment by isuruf** [comment]
Sorry, I was going to merge after tests pass and was offline when it did.

**Comment by jakirkham** [comment]
All good 🙂

If we missed anything in this PR, please let us know and we will be happy to add that in a new PR

**Pull request merged**
