### PR TITLE
1st checkin for v9.2.1 build.

### PR DESCRIPTION
**Pull request by billysuh7**
- remove ppc arch
- hardcode zlib version 1.2 because global pinning for zlib has become 1 recently
- update sysroot to 2.28 for aarch64

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by billysuh7** [comment]
Still in draft - will re-request review later.

**Comment by billysuh7** [comment]
@conda-forge-admin, please rerender

**Comment by billysuh7** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
cc: @mnicely for vis

**Comment by billysuh7** [comment]
@conda-forge-admin, please rerender

**Comment by billysuh7** [comment]
@conda-forge-admin, please rerender

**Comment by billysuh7** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
